name: BABYLON-ultra-dict
targets:
  BABYLON-ultra-dict:
    type: application
    platform: macOS
    deploymentTarget: "15.0"
    sources:
      - Sources/Babilon
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: dev.vaked.babylon-ultra-dict
      INFOPLIST_FILE: Resources/Info.plist
      DEVELOPMENT_TEAM: 7CFQYBX575
      SWIFT_VERSION: "6.0"
      MACOSX_DEPLOYMENT_TARGET: "15.0"
    entitlements:
      path: Resources/Babilon.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
